name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Prepare deployment files
      run: |
        # Create a dist directory for deployment
        mkdir -p dist
        
        # Copy the static files from public directory
        echo "Copying files from public directory..."
        cp -r public/* dist/
        
        # Verify we have the required files
        echo "Files prepared for deployment:"
        ls -la dist/
        
        # Check that index.html exists
        if [ ! -f "dist/index.html" ]; then
          echo "Error: index.html not found in deployment directory!"
          exit 1
        fi
        
    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy to gh-pages branch from ${{ github.sha }}'
